### ISSUE TITLE
Activity 1: Your First Caption

### ISSUE THREAD

**Issue by weshockley** [GH-DEV-WS-MNIT/Caption-This#2]
Using the API, I have just created a file with a random octocat for you to caption. In this activity, we will learn how to make changes to files in our GitHub repository.

- [ ] @emteach
- [ ] @weshockley
- [ ] @ASwenson22
- [ ] @BlazeFS
- [ ] @IamNotQuick
- [ ] @Krause94
- [ ] @Nichodaemus
- [ ] @Onggiverse
- [ ] @ahox0019
- [ ] @bkrotz
- [ ] @byklearning
- [ ] @czweber1
- [ ] @dwolf1234
- [ ] @grafix9876
- [ ] @jeffpalzermn
- [ ] @jvereide
- [ ] @lukebrandt
- [ ] @smaher1971
- [ ] @tiryx007

**Comment by BlazeFS** [comment]
👍
